language: ruby
os: osx
rvm: system

before_install:
  - brew update || brew update
  - export HOMEBREW_DEVELOPER="1"
install:
  - brew tap haraldf/kf5 file://$PWD
script:
  - CHANGED_FILES=($(git diff --name-only $TRAVIS_COMMIT_RANGE))
  - echo $CHANGED_FILES
  - tools/travis-ci.sh $CHANGED_FILES
